version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./server:/var/www/server
      - ./client:/var/www/client
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    links:
      - php
      - mysql
    depends_on:
      - mysql
  php:
    build: ./docker/php
    volumes:
      - ./server:/var/www/server
    working_dir: /var/www/server
    env_file:
      - .env
  node:
    build: ./docker/node
    working_dir: /var/www/client
    volumes:
      - ./client:/var/www/client
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    env_file:
    - .env
    container_name: enaza-mysql
